BulkyBookWeb/Areas/Admin/Controllers/CoverTypeController.cs
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using Microsoft.AspNetCore.Mvc;

namespace BulkyBookWeb.Controllers
{
    public class CoverTypeController : Controller
    {
        
        //private readonly ICategoryRepository db;
        //public CategoryController(ICategoryRepository db)

        private IUnitOfWork unitOfWork;

        public CoverTypeController(IUnitOfWork unitOfWork)
        {
            //dependency injections take cares of database object
            //this.db = db;

            this.unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            //List<Models.Category>? objCategoryList = db.Categories.ToList();
            IEnumerable<CoverType> objectCoverTypeList = unitOfWork.CoverType.GetAll();
            return View(objectCoverTypeList);
        }
        public IActionResult Create() { 
        return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public  IActionResult Create(CoverType CoverType) {
            if (ModelState.IsValid)
            {
                unitOfWork.CoverType.Add(CoverType);
                unitOfWork.Save();
                TempData["success"] = "CoverType created successfully";
                return RedirectToAction("Index");
            }
            return View(CoverType);

        }

        public IActionResult Edit(uint? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            CoverType CoverType = unitOfWork.CoverType.GetFirstOrDefault(u=>u.Id==id);

            if (CoverType == null)
            {
                return NotFound();
            }
            return View(CoverType);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(CoverType CoverType)
        {
            if (ModelState.IsValid)
            {
                unitOfWork.CoverType.Update(CoverType);
                unitOfWork.Save();
                TempData["success"] = "CoverType edited successfully.";
                return RedirectToAction("Index");
            }
            return View(CoverType);

        }
        public IActionResult Delete(uint? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            CoverType CoverType = unitOfWork.CoverType.GetFirstOrDefault(u=>u.Id == id);
            if (CoverType == null)
            {
                return NotFound();
            }
            return View(CoverType);
        }
        
       // [HttpPost,ActionName("Delete")] for explicit reference.

        //POST  method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(CoverType CoverType)
        {
            unitOfWork.CoverType.Remove(CoverType);
            unitOfWork.Save();
            TempData["success"] = "CoverType deleted successfully.";

            return RedirectToAction("Index");
        }
    }
}

BulkyBookWeb/Areas/Admin/Views/CoverType/Create.cshtml
@model CoverType
@{
    ViewData["Title"] = "Create";
}

<form method = "post" class = "border mt-3">
    
    <div class = "p-3 mt-4">
        <h2 class = "text-primary">Create Cover Type</h2>
    
        <div asp-validation-summary=All class="text-danger"></div>
        <div class="mb-3">
            <label class="" asp-for="Name"></label>
            <input asp-for="Name"  class="form-control"  />
            <span asp-validation-for=Name class="text-danger"></span>
        </div>
        <button type="submit" class = "btn btn-primary" style ="width:150px">Create</button>
        <a asp-controller="CoverType" asp-action = "Index"  class = "btn btn-secondary"  style ="width:150px">Back to the List</a>
    </div> 
    
</form>




<!--
 client-side validations ... 
-->

@section Scripts {
    @{
    <partial name="_ValidationScriptsPartial.cshtml"></partial>
    }
}

BulkyBookWeb/Areas/Admin/Views/CoverType/Delete.cshtml
@model CoverType
@{
    ViewData["Title"] = "Create";
}

@*
    if I were to create a post method named differently to actual action method.. asp-controller is defined implicitly. 
<form method = "post" asp-action="DeletePOST" class = "border mt-3">*@

<form method = "post" class = "border mt-3">
    @*
       
     passed the object into the view and it automatically set the input default values to object's properties. 
  *@
    <div class = "p-3 mt-4">
        <h2 class = "text-primary">Delete Category</h2>
    
        <div asp-validation-summary=All class="text-danger"></div>
        <div class="mb-3">
            <label class="" asp-for="Name"></label>
            <input asp-for="Name"  class="form-control" readonly  />
            <span asp-validation-for=Name class="text-danger"></span>
            
        </div>
        
        <button type="submit" class = "btn btn-danger" style ="width:150px">Delete</button>
        <a asp-controller="CoverType" asp-action = "Index"  class = "btn btn-secondary"  style ="width:150px">Back to the List</a>
    </div> 
    
</form>

BulkyBookWeb/Areas/Admin/Views/CoverType/Edit.cshtml
@model CoverType
@{
    ViewData["Title"] = "Create";
}

<form method = "post" class = "border mt-3">
    @*
     passed the object into the view and it automatically set the input default values to object's properties. 
  *@
    <div class = "p-3 mt-4">
        <h2 class = "text-primary">Edit Cover Type</h2>
    
        <div asp-validation-summary=All class="text-danger"></div>
        <div class="mb-3">
            <label class="" asp-for="Name"></label>
            <input asp-for="Name"  class="form-control"  />
            <span asp-validation-for=Name class="text-danger"></span>
            
        </div>
        <button type="submit" class = "btn btn-primary" style ="width:150px">Update</button>
        <a asp-controller="CoverType" asp-action = "Index"  class = "btn btn-secondary"  style ="width:150px">Back to the List</a>
    </div> 
    
</form>




<!--
 client-side validations ... 
-->

@section Scripts {
    @{
    <partial name="_ValidationScriptsPartial.cshtml"></partial>
    }
}

BulkyBookWeb/Areas/Admin/Views/CoverType/Index.cshtml
@model IEnumerable<CoverType> 
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    
}

@* i displayed the temporary message here because after every crud operation program redirects the user to this page.   *@
<div class="container p-3">
    <div class="row pt-4">
        <div class ="col-6">
            <h2 class="text-primary">CoverType Controller</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="CoverType" asp-action="Create" class="btn-primary btn">Create New</a>
        </div>
    </div>
    <br />  
    
    <table class = "table table-bordered table-striped">
        <thead>
            <tr>
                <th>Cover Type Name</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
           {
            <tr>

                <td width="70%">
                    @item.Name
                </td>
                <td>
                    <a asp-controller="CoverType" asp-action="Edit" asp-route-id=@item.Id class ="btn btn-primary mx-2"><i class="bi bi-pencil-square"></i> Edit</a>
                    <a asp-controller="CoverType" asp-action="Delete" asp-route-id=@item.Id class ="btn btn-danger mx-2"><i class="bi bi-trash"></i> Delete</a>
                </td>
            </tr>   
           }
        </tbody>
    </table>
</div>